# Generated by Django 2.0.1 on 2018-02-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_patient',
            new_name='is_doctor',
        ),
    ]
